$ gcc -I/usr/include/postgresql/ -o libpqex1 libpqex1.c
/tmp/cc99KH8g.o: In function `exit_nicely':
libpqex1.c:(.text+0x14): undefined reference to `PQfinish'
/tmp/cc99KH8g.o: In function `main':
libpqex1.c:(.text+0x3a): undefined reference to `PQconnectdb'
libpqex1.c:(.text+0x4a): undefined reference to `PQstatus'
libpqex1.c:(.text+0x5a): undefined reference to `PQerrorMessage'
libpqex1.c:(.text+0x93): undefined reference to `PQexec'
libpqex1.c:(.text+0xa3): undefined reference to `PQresultStatus'
libpqex1.c:(.text+0xb4): undefined reference to `PQerrorMessage'
libpqex1.c:(.text+0xdc): undefined reference to `PQclear'
libpqex1.c:(.text+0xf4): undefined reference to `PQclear'
libpqex1.c:(.text+0x105): undefined reference to `PQexec'
libpqex1.c:(.text+0x115): undefined reference to `PQresultStatus'
libpqex1.c:(.text+0x126): undefined reference to `PQerrorMessage'
libpqex1.c:(.text+0x14e): undefined reference to `PQclear'
libpqex1.c:(.text+0x166): undefined reference to `PQclear'
libpqex1.c:(.text+0x177): undefined reference to `PQexec'
libpqex1.c:(.text+0x187): undefined reference to `PQresultStatus'
libpqex1.c:(.text+0x198): undefined reference to `PQerrorMessage'
libpqex1.c:(.text+0x1c0): undefined reference to `PQclear'
libpqex1.c:(.text+0x1d8): undefined reference to `PQnfields'
libpqex1.c:(.text+0x1f5): undefined reference to `PQfname'
libpqex1.c:(.text+0x243): undefined reference to `PQgetvalue'
libpqex1.c:(.text+0x27b): undefined reference to `PQntuples'
libpqex1.c:(.text+0x28c): undefined reference to `PQclear'
libpqex1.c:(.text+0x29d): undefined reference to `PQexec'
libpqex1.c:(.text+0x2ad): undefined reference to `PQclear'
libpqex1.c:(.text+0x2be): undefined reference to `PQexec'
libpqex1.c:(.text+0x2ce): undefined reference to `PQclear'
libpqex1.c:(.text+0x2da): undefined reference to `PQfinish'
collect2: error: ld returned 1 exit status
